# Generated by Django 4.1.2 on 2022-10-15 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('foto', models.ImageField(upload_to='')),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=100000000)),
                ('importado', models.BooleanField(default=False)),
                ('estoque_atual', models.IntegerField()),
                ('estoque_min', models.IntegerField(blank=True)),
                ('data', models.DateField(blank=True)),
                ('avaliacao', models.IntegerField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.categoria')),
                ('tamanho', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produto.tamanho')),
            ],
        ),
    ]
