# Generated by Django 4.1.2 on 2022-10-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='avaliacao',
            field=models.IntegerField(blank=True),
        ),
    ]
