# Generated by Django 3.2.16 on 2022-10-14 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_alter_usuario_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
    ]
