# Generated by Django 3.2.16 on 2022-10-17 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_token_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token_login',
            old_name='login_hash',
            new_name='login_codigo',
        ),
    ]
